### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by coolacid** [VE3LSR/pynaads#12]
Traceback (most recent call last):
  File "./pelmorex.py", line 60, in <module>
    run()
  File "./pelmorex.py", line 39, in run
    for q in item:
  File "/home/Repos/CoolAcid/NAADAlerts/pynaads/pynaads/event.py", line 138, in __next__
    if self.area >= len(self.event['info'][self.info]['area']):
  File "/home/Repos/CoolAcid/NAADAlerts/pynaads/pynaads/event.py", line 165, in genIDs
    else:
TypeError: must be str, not list

**Comment by coolacid** [comment]
7c0c1c4be8cc9d9ae4ca2494d71e87fe141317ac fixes this
